fix(linear-vesting-power): handle multiple vesting lines
morpho-labs/snapshot-strategies pull request #1
Opened 2022-11-26 16:18 UTC by julien-devatom

Changes proposed in this pull request:
- Map over ids instead of finding one linear vesting line

2022-11-26 16:36 UTC, MerlinEgalite requested changes
Just a suggestion. I think there's no vesting yanked yet so I can approve the PR for now if needed

2022-11-26 16:36 UTC, MerlinEgalite commented on src/strategies/linear-vesting-power/index.ts
> +        if (!(id && totalAccrued && totalVested && bgn && fin)) return vp;
I think we should test somewhere if a vesting is yanked or not. So that we don't add vesting power that should not be added.

2022-11-26 16:50 UTC, julien-devatom commented on src/strategies/linear-vesting-power/index.ts
> +        if (!(id && totalAccrued && totalVested && bgn && fin)) return vp;
The DSSVest yank operation is setting the `end` to the current block timestamp, and defining the `tot` to the current vested amount (check [here](https://github.com/makerdao/dss-vest/blob/master/src/DssVest.sol#L352))
And, when we are computing the linear vesting power, we are handling this case, because `fin` is modified (check [here](https://github.com/morpho-labs/snapshot-strategies/blob/fix/multiple-vesting-lines/src/strategies/linear-vesting-power/index.ts#L116))

2022-11-26 16:56 UTC, MathisGD approved these changes
LGTM

2022-11-27 09:26 UTC, oumar-fall approved these changes

2022-11-27 09:48 UTC, MerlinEgalite approved these changes
LGTM

2022-11-27 09:48 UTC, MerlinEgalite commented on src/strategies/linear-vesting-power/index.ts
> +        if (!(id && totalAccrued && totalVested && bgn && fin)) return vp;
Ok then all good!

2022-11-28 08:35 UTC, Rubilmax approved these changes

2022-12-01 14:20 UTC, merged